### ISSUE TITLE
Metadata edit performance: Ask for a search before showing any results

### ISSUE THREAD

**Issue by StephenChan** [coralnet/coralnet#130]
Currently, after the user clicks "Metadata", they get a metadata grid of ALL their images. The grid is somewhat slow to load and rather sluggish to interact with once you get to a few hundred images. And some sources have thousands.

It would be better to make the user submit a search before showing anything, so if they have thousands of images, they can apply some filters first to minimize bombardment on their browser. (The Patches page already behaves like this, so we just copy that behavior.) We could possibly only make the user do this if they have over ~300 images, but... that's going to be true for most of our serious users anyway.

**Comment by beijbom** [comment]
I dunno. This issue seems a bit hacky. I meant, it seems like a in use-case to want to view/edit all rows. In which case this is useless. Pagination seems like a better solution. In particular if paired with a “select all across all pages” button.

**Comment by StephenChan** [comment]
I guess this is more of an 'interim solution' idea if pagination was too complicated. But if we don't implement 'select all across all pages' yet, I think pagination should be pretty simple, in which case I agree this issue shouldn't be needed.

**Comment by kriegman** [comment]
Another possibility that may be easier than pagination is to make the
initial sql call to request the meta data info with say limit=50 and then
add
a "see rest" button which will make the query without the limit. That would
make the database query faster and at least
initial displays fast.

**Comment by StephenChan** [comment]
Done in PR #493. Again, lazy interim solution.
