### ISSUE TITLE
Confirmed image missing annotations

### ISSUE THREAD

**Issue by beijbom** [coralnet/coralnet#225]
Check out this image:
<img width="968" alt="Screen Shot 2019-08-11 at 10 11 10 PM" src="https://user-images.githubusercontent.com/857711/69950866-fecb0280-14a8-11ea-8e7e-bbc2a2ce8247.png">

<img width="987" alt="Screen Shot 2019-08-11 at 10 11 00 PM" src="https://user-images.githubusercontent.com/1128855/62846441-1cb7f180-bc85-11e9-912e-9e0594c59744.png">

https://coralnet.ucsd.edu/image/646341/annotation/tool/

it is confirmed, but not fully annotated. 

Ideally, the "confirmed" boolean should be replaced by a property that asserts if all points are annotated. But it's a challenge to make that fast enough, I presume. Still, I'd advocate for doing just that.

We also need to write a crawler to check how common this problem is.

**Comment by StephenChan** [comment]
I'm not sure if I've observed this particular issue anytime in recent years, and there have been various gradual changes to image status updating/checking that could have fixed it. Seems reasonable to close this.
