### ISSUE TITLE
Move production server specifics to a coralnet-system repo

### ISSUE THREAD

**Issue by StephenChan** [coralnet/coralnet#253]
This is a step towards open-sourcing this repo (issue #176). Reasoning:

- Separation of concerns and professionalism. You don't expect to visit a website's code repo and find the settings for their mail server and web proxy. Those server settings just aren't very related to how the web application itself works, so including those things in the repo is kind of off-topic and can be confusing.

- There are [a variety of reasons](https://opensource.google/docs/why/) to open-source, but they don't seem to apply as much to server configuration. CoralNet is relatively unique because it uses machine learning, has a CPCe-style interface, provides a workflow for benthic image annotation, uses certain Django apps in tandem, and so on. Those can be nice contributions to the open source community. Configuration of nginx or Ubuntu? That's probably been done hundreds of thousands of times already.

- Server config tends to be more security sensitive in nature than application logic. Of course, application logic can also have security flaws, but security holes in server config are generally easier to find (again, because it's the less-unique part of our website), and attacking the 'outer layers' of a server (e.g. the Ubuntu instance, as opposed to its web app interface) can have more damaging results. Ideally, we won't rely on security-through-obscurity in most cases, but due to limited resources, we can't apply every patch on the 0th day and be security masterminds on every topic.

So, what could be moved to a new `coralnet-system` repo?

- **Production-specific docs**: PR #252 is my attempt to delineate what's production-specific or not in the docs. Basically, any docs relevant to setting up and running a development environment would stay in this repo. For the `design` section of the docs, any design topics concerning the code in this repo would stay in this repo. Other docs are production (or staging) specific and would go in the system repo.

- **Production-specific GitHub issues**: Issues can be transferred from one repo to another, [as described here](https://help.github.com/en/articles/transferring-an-issue-to-another-repository). The main downside to doing this is that we'll need to track milestones and project boards for `coralnet` and `coralnet-system` separately. However, the separation and security concerns above definitely apply to these issues, so I think it's best to move them.

- **s3_sync script**: Currently at `scripts/s3_sync.py`. It makes sense to also move this if we are moving all AWS docs to `coralnet-system`.

- **`makenginxconfig` management command**: Naturally, this is a server config detail. If we move this to `coralnet-system`, we could change this from a management command to a standalone Python script. It would have to import Django settings from the main CoralNet project, but that [should be doable](https://stackoverflow.com/a/39724171). Alternatively, we could fashion `coralnet-system` as a Django app with its own Django management command(s).

There are other bits which are largely server-specific, but they're also somewhat tied to the Django project for now. For example, the `maintenanceon` and `maintenanceoff` management commands write to a `MAINTENANCE_STATUS_FILE_PATH`, so if we remove those management commands, it also makes sense to move that file path setting to `coralnet-system`... as well as the `get_maintenance_time` template tag which uses `MAINTENANCE_STATUS_FILE_PATH`. At the very least, it'll take more effort to deal with fragmenting the Django project to this degree. It's probably best to start simple for now.

Any other ideas for things we can move to `coralnet-system`?

**Comment by StephenChan** [comment]
@beijbom With the GitHub changes to plan offerings, maybe this is worth another look? No rush though.

![2020-04-14_Github-free-team-private-repositories](https://user-images.githubusercontent.com/857711/79284964-f92af380-7e70-11ea-900a-0e7cf6a8152a.png)

**Comment by beijbom** [comment]
Yeah. That's great. We should def. do this. Perhaps after the Beta2 release?

**Comment by StephenChan** [comment]
Sounds good. I can make a separate issue so we don't have to re-open this one.
