### ISSUE TITLE
Download Coralnet Dataset

### ISSUE THREAD

**Issue by premchedella** [coralnet/coralnet#514]
I would like to download Coralnet Dataset.

May I know how to download the entire Coralnet Dataset.  

Thank you in advance.

**Comment by StephenChan** [comment]
Hi Prem - we don't currently have a roadmap for providing site-wide data downloads (presuming that you're asking about images from all public sources). We're still trying to address concerns about the web server load and responsiveness, so it'll probably be a while before we prioritize making such a large amount of data easily downloadable.

You've seen Andrew's post from the Google Group though, and if his explanation is still available (involves page-scraping if I remember correctly), it's fine if you use that method.

**Comment by premchedella** [comment]
Hello @StephenChan ,

Thank you so much for the message and I got the reason behind not providing site wide data download.

I have seen Andrew's post and I understand how images are shown from https://coralnet.ucsd.edu/source/about/ to the actual images.  I wrote a python code to down images using page scraping.
