### ISSUE TITLE
Images for the corresponding label

### ISSUE THREAD

**Issue by premchedella** [coralnet/coralnet#515]
Hello,

I investigated how to get the whole image list for the corresponding label but I didn't find it.  

All labels can be obtained from [Label list.](https://coralnet.ucsd.edu/label/list/)
For example, **Label 51_tabular_hard_coral** points to [https://coralnet.ucsd.edu/label/3749/](https://coralnet.ucsd.edu/label/3749/).  How can get the list of images that fall under the label,  **Label 51_tabular_hard_coral**?

**Comment by StephenChan** [comment]
I've replied here: https://groups.google.com/g/coralnet-users/c/VBAh0mvw_wM

**Comment by premchedella** [comment]
Thanks for the response @StephenChan.
