### ISSUE TITLE
Activation email not received

### ISSUE THREAD

**Issue by jorisguerin** [coralnet/coralnet#533]
Hi,

I am trying to register to the CoralNet website to collaborate on an ongoing project but I don't receive the activation email.
I tried three consecutive days, with two different emails but it does not work.

Could you help me with this issue?

Best,
Joris

**Comment by StephenChan** [comment]
Hi Joris,

I looked through the recent registration attempts; it looks like the .edu email had problems with activation, but the .fr email might have succeeded. Are you able to log in now?
