### ISSUE TITLE
Let source A's classifier be used by source B (baseline functionality)

### ISSUE THREAD

**Issue by StephenChan** [coralnet/coralnet#537]
There are several ideas going on in issue #150 - I wanted to make this separate issue to establish some baseline functionality (and associated limitations) as a more achievable issue in the short term. Here's an idea for that:

- Source B can only specify the desired classifier ID at source-creation time. When this happens, it automatically sets up source B's labelset to match source A's labelset.

- There will be a check to ensure that source B's creator has view-access to the source which owns the specified classifier. However, the interface for choosing the classifier might not be intuitive or informative yet. Perhaps just a number-input field for the ID.

- Source B won't be able to specify a different classifier after source creation. Source B won't be able to change its labelset after creation, unless the classifier gets deleted (e.g. source A's labelset changes), in which case source B permanently reverts to a "traditional" source which trains its own classifier.

- This feature would be available to anyone who can create a source (so, any registered CoralNet user), but it would have a note that it's in beta phase and has the limitations laid out above.

Note that Source B would point to a classifier ID, not a source ID, so that Source B doesn't worry about the classifier or the labelset changing from underneath it. (Again though, it's another story if the classifier's deleted - which happens if Source A changes its labelset, changes its feature extractor, or is deleted.)

**Comment by kriegman** [comment]
So, this seems like a version of a published "robot" for source A that is
used by source B. A published robot (say from source A) will basically be a
specific classifier, which implies a specific labelset and feature
extractor. So, in this scenario, source B is using a robot from source A.
This issue, might be addressed in the context fo "published robots" and a
more involved semantic of a hierarchy of sources or source inheritance.

**Comment by StephenChan** [comment]
Right, I edited in this sentence to clarify what types of changes in source A would upend source B's setup:

> (Again though, it's another story if the classifier's deleted - which happens if Source A changes its labelset, changes its feature extractor, or is deleted.)

Yes, maybe it makes the most sense to consider source B as inheriting from source A in this case. Though if we could later make this setup more flexible, saying that source B will be able to change which classifier it points to (even a classifier of a different source), then we might conceptualize it differently.

**Comment by StephenChan** [comment]
Done in PR #549:

> * Source B can only specify the desired classifier ID at source-creation time. When this happens, it automatically sets up source B's labelset to match source A's labelset.

Went beyond this, making the classifier ID specifiable in both the new and edit source forms.

> * There will be a check to ensure that source B's creator has view-access to the source which owns the specified classifier. However, the interface for choosing the classifier might not be intuitive or informative yet. Perhaps just a number-input field for the ID.

Yes, just a number-input field.

> * Source B won't be able to specify a different classifier after source creation. Source B won't be able to change its labelset after creation, unless the classifier gets deleted (e.g. source A's labelset changes), in which case source B permanently reverts to a "traditional" source which trains its own classifier.
> 
>   * This feature would be available to anyone who can create a source (so, any registered CoralNet user), but it would have a note that it's in beta phase and has the limitations laid out above.

- Again, supported by new and edit source forms.
- Can still change labelset after source creation, as long as you've switched back to train-own-classifiers mode; you can later switch back to use-other-classifier mode as long as the labelset matches.
- Neither mode is permanent.
- If in use-other-classifier mode, and the classifier gets deleted, the source ends up in a state where it doesn't have a deployed classifier. This is a perfectly valid state, and the source owner can reconfigure at any time to pick another classifier or switch to train-mode.
- No beta phase note on the source form, since this functionality shouldn't be particularly limited/buggy compared to other site functions. However, the blog post announcement will say it's still new and things are subject to changes/fixes.

> Note that Source B would point to a classifier ID, not a source ID, so that Source B doesn't worry about the classifier or the labelset changing from underneath it. (Again though, it's another story if the classifier's deleted - which happens if Source A changes its labelset, changes its feature extractor, or is deleted.)

Hmm... I'm not exactly sure what I was conveying here. But Source A changing its labelset or extractor still means that Source A's own classifiers get deleted, as was the case before. And as for what happens when B is using A's classifier and A's classifier is deleted, see above.
